server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 102700
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.zzu.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
host: 127.0.0.1
port: 9090